/**
 * @file
 * @brief Implements NMT master behavior validation with a Lely BasicSlave.
 */

#include "nmt_master_process.h"

#include "canopen_config.h"

#include <lely/coapp/node.hpp>
#include <lely/coapp/sdo_error.hpp>
#include <lely/coapp/slave.hpp>

#include <spdlog/spdlog.h>

#include <array>
#include <chrono>
#include <cstddef>
#include <condition_variable>
#include <cstdint>
#include <functional>
#include <mutex>
#include <system_error>

namespace {

/** One expected callback in the NMT-master validation sequence. */
struct NmtMasterStep {
    lely::canopen::NmtCommand command; /**< Command expected from Lely. */
    const char* description; /**< Diagnostic text for the transition. */
    bool restoreHeartbeat; /**< true when reset completion must restart heartbeat. */
};

/** Queue capacity for NMT callbacks received before the waiter consumes them. */
constexpr std::size_t kNmtCommandQueueCapacity = 16;

/** Runtime state shared by the NMT command callback and control thread. */
struct NmtCommandObserverState {
    std::mutex mutex; /**< Protects all state members below. */
    std::condition_variable condition; /**< Wakes the waiting control thread. */
    /** Fixed queue preserving callback arrival order. */
    std::array<lely::canopen::NmtCommand, kNmtCommandQueueCapacity> queue{};
    std::size_t head = 0; /**< Index of the next queued command to consume. */
    std::size_t count = 0; /**< Number of queued commands. */
    bool overflow = false; /**< true if callback production exceeded capacity. */
    bool active = false; /**< true while one validation run owns OnCommand. */
};

NmtCommandObserverState g_nmt_command_observer;

const NmtMasterStep kStartStep = {
    lely::canopen::NmtCommand::START, "Start Remote Node", false};
const NmtMasterStep kStopStep = {
    lely::canopen::NmtCommand::STOP, "Stop Remote Node", false};
const NmtMasterStep kPreOperationalStep = {
    lely::canopen::NmtCommand::ENTER_PREOP, "Enter Pre-operational", false};
const NmtMasterStep kResetCommunicationStep = {
    lely::canopen::NmtCommand::RESET_COMM, "Reset Communication", false};
const NmtMasterStep kResetCommunicationCompletionStep = {
    lely::canopen::NmtCommand::ENTER_PREOP,
    "Reset Communication completion", true};
const NmtMasterStep kResetNodeStep = {
    lely::canopen::NmtCommand::RESET_NODE, "Reset Node", false};
const NmtMasterStep kResetNodeCommunicationStep = {
    lely::canopen::NmtCommand::RESET_COMM,
    "Reset Node communication reset", false};
const NmtMasterStep kResetNodeCompletionStep = {
    lely::canopen::NmtCommand::ENTER_PREOP, "Reset Node completion", true};
const NmtMasterStep kFixtureAutoStartStep = {
    lely::canopen::NmtCommand::START,
    "Fixture auto-start after reset", false};
const NmtMasterStep kFixturePreOperationalStep = {
    lely::canopen::NmtCommand::ENTER_PREOP,
    "Fixture PRE-OP normalization", false};
const NmtMasterStep kFinalStartStep = {
    lely::canopen::NmtCommand::START, "Final Start", false};

/**
 * @brief Convert an NMT command value to a concise diagnostic name.
 *
 * @param command Command specifier received by the software slave.
 * @return Static command name used in logs.
 */
const char* nmtCommandName(lely::canopen::NmtCommand command) noexcept
{
    switch (command) {
    case lely::canopen::NmtCommand::START:
        return "START";
    case lely::canopen::NmtCommand::STOP:
        return "STOP";
    case lely::canopen::NmtCommand::ENTER_PREOP:
        return "PREOP";
    case lely::canopen::NmtCommand::RESET_NODE:
        return "RESET_NODE";
    case lely::canopen::NmtCommand::RESET_COMM:
        return "RESET_COMM";
    }
    return "UNKNOWN";
}

/**
 * @brief Publish an NMT command received or generated by the software slave.
 *
 * For START, STOP and ENTER_PREOP, Lely calls OnCommand() from the matching NMT
 * state entry. RESET_NODE and RESET_COMM similarly publish their reset-state
 * entries, and the subsequent internal ENTER_PREOP callback confirms reset
 * completion back to the normal slave state.
 *
 * @param command NMT command reported by Lely.
 */
void nmtCommandCallback(lely::canopen::NmtCommand command) noexcept
{
    NmtCommandObserverState& state = g_nmt_command_observer;
    {
        std::lock_guard<std::mutex> lock(state.mutex);
        if (!state.active) {
            return;
        }

        if (state.count >= kNmtCommandQueueCapacity) {
            /* Keep the original queue contents intact. The waiter reports the
             * overflow explicitly instead of silently losing event order. */
            state.overflow = true;
        } else {
            const std::size_t tail =
                (state.head + state.count) % kNmtCommandQueueCapacity;
            state.queue[tail] = command;
            ++state.count;
        }
    }
    state.condition.notify_all();
}

/**
 * @brief Register a fresh command observer for one validation run.
 *
 * @param slave Software slave whose NMT commands are observed.
 */
void registerNmtCommandObserver(lely::canopen::BasicSlave& slave)
{
    NmtCommandObserverState& state = g_nmt_command_observer;
    {
        std::lock_guard<std::mutex> lock(state.mutex);
        /* A new validation run must not consume callbacks from a previous run. */
        state.head = 0;
        state.count = 0;
        state.overflow = false;
        state.active = true;
    }
    slave.OnCommand(nmtCommandCallback);
}

/**
 * @brief Remove the NMT command callback after validation completes.
 *
 * @param slave Software slave that owns the callback slot.
 */
void unregisterNmtCommandObserver(lely::canopen::BasicSlave& slave)
{
    NmtCommandObserverState& state = g_nmt_command_observer;
    {
        std::lock_guard<std::mutex> lock(state.mutex);
        state.active = false;
    }
    slave.OnCommand(
        std::function<void(lely::canopen::NmtCommand)>{});
    {
        std::lock_guard<std::mutex> lock(state.mutex);
        state.head = 0;
        state.count = 0;
        state.overflow = false;
    }
}

/**
 * @brief Configure the software peer Producer Heartbeat used by MCU supervision.
 *
 * Lely restores communication parameters during RESET_COMM. This helper is
 * used when validation starts and after reset completion reaches PRE-OP.
 *
 * @param slave Software slave whose local 0x1017 is configured.
 * @return true when 0x1017 is updated successfully; otherwise false.
 */
bool configurePeerHeartbeat(lely::canopen::BasicSlave& slave)
{
    std::error_code error;
    slave.Write<uint16_t>(0x1017, 0,
                          static_cast<uint16_t>(CANOPEN_PEER_HEARTBEAT_MS),
                          error);
    if (error) {
        spdlog::error(
            "Unable to configure slave peer heartbeat: node={} period={}ms error={}",
            CANOPEN_PEER_NODE_ID, CANOPEN_PEER_HEARTBEAT_MS,
            error.message());
        return false;
    }
    return true;
}

/**
 * @brief Determine whether Lely auto-starts the peer after an NMT reset.
 *
 * Lely uses bit 2 of object 0x1F80 for slave startup. A missing 0x1F80 is
 * treated by Lely as value zero, which also enables automatic Operational
 * startup after reset. The test reads this contract without modifying the EDS.
 *
 * @param slave Software slave whose local NMT startup value is inspected.
 * @param autoStarts Receives true when reset startup enters Operational.
 * @return true when the startup behavior is determined; otherwise false.
 */
bool peerAutoStartsAfterReset(lely::canopen::BasicSlave& slave,
                              bool& autoStarts)
{
    std::error_code error;
    const uint32_t startup = slave.Read<uint32_t>(0x1F80, 0, error);
    if (!error) {
        autoStarts = (startup & 0x04U) == 0U;
        spdlog::info(
            "Peer NMT startup: value=0x{:08x} auto_start_after_reset={}",
            startup, autoStarts);
        return true;
    }

    if (error == lely::canopen::SdoErrc::NO_OBJ) {
        autoStarts = true;
        spdlog::info(
            "Peer NMT startup object 0x1F80 absent; Lely default "
            "auto_start_after_reset=true");
        return true;
    }

    spdlog::error("Unable to read peer NMT startup object 0x1F80: {}",
                  error.message());
    return false;
}

/**
 * @brief Wait for one queued NMT callback.
 *
 * @param command Receives the next queued command.
 * @param expectedDescription Diagnostic text used when the wait times out.
 * @return true when one command is consumed; otherwise false on timeout or
 *         queue overflow.
 */
bool waitForNmtCommand(lely::canopen::NmtCommand& command,
                       const char* expectedDescription)
{
    NmtCommandObserverState& state = g_nmt_command_observer;
    const std::chrono::milliseconds timeout(
        CANOPEN_NMT_MASTER_STEP_TIMEOUT_MS);
    std::unique_lock<std::mutex> lock(state.mutex);
    const bool observed = state.condition.wait_for(
        lock, timeout,
        [&state]() { return state.count > 0 || state.overflow; });
    if (!observed) {
        spdlog::error("NMT master step timed out: expected={}",
                      expectedDescription);
        return false;
    }
    if (state.overflow) {
        spdlog::error("NMT master callback queue overflowed");
        return false;
    }

    command = state.queue[state.head];
    state.head = (state.head + 1) % kNmtCommandQueueCapacity;
    --state.count;
    return true;
}

/**
 * @brief Wait for one optional NMT callback during a bounded observation window.
 *
 * @param command Receives the queued command when @p observed is true.
 * @param observed Receives true when one callback is consumed.
 * @param timeout Maximum observation interval.
 * @return true when the window completes normally; false on queue overflow.
 */
bool waitForOptionalNmtCommand(lely::canopen::NmtCommand& command,
                               bool& observed,
                               const std::chrono::milliseconds& timeout)
{
    NmtCommandObserverState& state = g_nmt_command_observer;
    std::unique_lock<std::mutex> lock(state.mutex);
    observed = state.condition.wait_for(
        lock, timeout,
        [&state]() { return state.count > 0 || state.overflow; });
    if (!observed) {
        return true;
    }
    if (state.overflow) {
        spdlog::error("NMT master callback queue overflowed");
        return false;
    }

    command = state.queue[state.head];
    state.head = (state.head + 1) % kNmtCommandQueueCapacity;
    --state.count;
    return true;
}

/**
 * @brief Wait for exactly one queued callback and verify its command.
 *
 * @param slave Software slave whose heartbeat is restored after reset completion.
 * @param step Expected command transition.
 * @return true when the next callback matches the expected command; otherwise
 *         false on timeout, queue overflow or mismatch.
 */
bool waitForNmtMasterStep(lely::canopen::BasicSlave& slave,
                          const NmtMasterStep& step)
{
    lely::canopen::NmtCommand command{};
    if (!waitForNmtCommand(command, step.description)) {
        return false;
    }

    if (command != step.command) {
        spdlog::error(
            "Unexpected NMT command: expected={} actual={}",
            nmtCommandName(step.command),
            nmtCommandName(command));
        return false;
    }

    /* RESET_COMM restores 0x1017 to the EDS/DCF default. Re-enable Producer
     * Heartbeat only after Lely reaches the subsequent PRE-OP callback; doing
     * it at RESET_COMM entry is too early because reset would overwrite it. */
    if (step.restoreHeartbeat && !configurePeerHeartbeat(slave)) {
        return false;
    }

    spdlog::info("NMT master step passed: {} command={}", step.description,
                 nmtCommandName(command));
    return true;
}

/**
 * @brief Resolve the deterministic initial fixture preparation path.
 *
 * The Host reads the unchanged local 0x1F80 startup contract. If reset startup
 * auto-enters Operational, the DUT must first send ENTER_PREOP. Otherwise the
 * peer is already PRE-OP and the first observed command is the formal START.
 *
 * @param autoStartAfterReset true when Lely startup auto-enters Operational.
 * @param formalStartObserved Receives true when the formal START callback was
 *                            consumed directly without fixture preparation.
 * @return true when the expected initial path is observed; otherwise false.
 */
bool enterPreOperational(bool autoStartAfterReset,
                         bool& formalStartObserved)
{
    lely::canopen::NmtCommand command{};
    formalStartObserved = false;
    if (!waitForNmtCommand(command,
                           autoStartAfterReset
                               ? "fixture PRE-OP preparation"
                               : "formal START")) {
        return false;
    }

    if (autoStartAfterReset) {
        if (command != lely::canopen::NmtCommand::ENTER_PREOP) {
            spdlog::error(
                "Unexpected initial NMT command: expected=PREOP actual={}",
                nmtCommandName(command));
            return false;
        }
        spdlog::info(
            "CANopen slave peer prepared by DUT: node={} state=PRE-OP",
            CANOPEN_PEER_NODE_ID);
        return true;
    }

    if (command != lely::canopen::NmtCommand::START) {
        spdlog::error(
            "Unexpected initial NMT command: expected=START actual={}",
            nmtCommandName(command));
        return false;
    }

    formalStartObserved = true;
    spdlog::info(
        "CANopen slave peer starts in PRE-OP; formal START observed directly");
    return true;
}

/**
 * @brief Verify the deterministic post-reset fixture branch and formal command.
 *
 * When 0x1F80 startup auto-enters Operational, Lely must report the fixture
 * START and the DUT must normalize it with ENTER_PREOP before the next formal
 * command. If auto-start is disabled, the formal command must arrive directly.
 *
 * @param slave Software slave used for exact callback verification.
 * @param formalStep Next formal MCU command expected after reset completion.
 * @param autoStartAfterReset true when reset startup auto-enters Operational.
 * @return true when the expected fixture branch and formal command are valid.
 */
bool waitForFormalCommandAfterReset(lely::canopen::BasicSlave& slave,
                                    const NmtMasterStep& formalStep,
                                    bool autoStartAfterReset)
{
    if (!autoStartAfterReset) {
        return waitForNmtMasterStep(slave, formalStep);
    }

    if (!waitForNmtMasterStep(slave, kFixtureAutoStartStep)
        || !waitForNmtMasterStep(slave, kFixturePreOperationalStep)) {
        return false;
    }

    return waitForNmtMasterStep(slave, formalStep);
}

/**
 * @brief Keep the final Operational peer alive through two producer heartbeats.
 *
 * The MCU declares the final START step complete only after receiving an
 * Operational heartbeat. Ensuring Producer Heartbeat remains enabled after the
 * START callback and keeping the event loop alive for two full periods gives
 * the MCU two heartbeat opportunities before the Host leaves the Slave role.
 * No further NMT callback is valid after the formal final START.
 *
 * @param slave Software slave whose final heartbeat configuration is verified.
 * @return true when heartbeat remains enabled and no extra NMT callback occurs
 *         through the confirmation window.
 */
bool keepPeerAliveForFinalHeartbeat(lely::canopen::BasicSlave& slave)
{
    if (!configurePeerHeartbeat(slave)) {
        return false;
    }

    const std::chrono::milliseconds heartbeatPeriod(CANOPEN_PEER_HEARTBEAT_MS);
    const std::chrono::milliseconds confirmationWindow = heartbeatPeriod * 2;
    spdlog::info(
        "Final START observed; keeping peer alive for {}ms heartbeat confirmation window",
        confirmationWindow.count());

    lely::canopen::NmtCommand command{};
    bool observed = false;
    if (!waitForOptionalNmtCommand(command, observed, confirmationWindow)) {
        return false;
    }
    if (observed) {
        spdlog::error(
            "Unexpected NMT command during final heartbeat confirmation: actual={}",
            nmtCommandName(command));
        return false;
    }

    std::error_code error;
    const uint16_t configuredHeartbeat = slave.Read<uint16_t>(0x1017, 0, error);
    if (error) {
        spdlog::error("Unable to read final peer heartbeat configuration: {}",
                      error.message());
        return false;
    }
    if (configuredHeartbeat != static_cast<uint16_t>(CANOPEN_PEER_HEARTBEAT_MS)) {
        spdlog::error(
            "Peer heartbeat changed during final confirmation: expected={}ms actual={}ms",
            CANOPEN_PEER_HEARTBEAT_MS, configuredHeartbeat);
        return false;
    }
    spdlog::info("Final heartbeat confirmation window elapsed");
    return true;
}

/**
 * @brief Verify the post-RESET_NODE fixture branch and formal final START.
 *
 * The startup contract is known before validation. When reset startup
 * auto-enters Operational, the final path must contain an internal fixture
 * START, DUT PREOP normalization, and then a distinct formal START. This
 * prevents an absent PREOP callback from being misclassified as success.
 *
 * @param slave Software slave used for heartbeat confirmation.
 * @param autoStartAfterReset true when reset startup auto-enters Operational.
 * @return true when the formal final START is confirmed; otherwise false.
 */
bool waitForFinalStartAfterReset(lely::canopen::BasicSlave& slave,
                                 bool autoStartAfterReset)
{
    if (autoStartAfterReset
        && (!waitForNmtMasterStep(slave, kFixtureAutoStartStep)
            || !waitForNmtMasterStep(slave, kFixturePreOperationalStep))) {
        return false;
    }

    if (!waitForNmtMasterStep(slave, kFinalStartStep)) {
        return false;
    }
    return keepPeerAliveForFinalHeartbeat(slave);
}

} // namespace

int nmtMasterProcess(lely::canopen::BasicSlave& slave)
{
    int result = 1;
    bool autoStartAfterReset = false;
    bool initialStartObserved = false;

    registerNmtCommandObserver(slave);

    if (!peerAutoStartsAfterReset(slave, autoStartAfterReset)) {
        goto cleanup;
    }

    /* BasicSlave::Reset() already completed before this process starts. Enable
     * Producer Heartbeat only after the observer is active, then let the MCU
     * normalize the peer to PRE-OP without modifying the MCU-provided EDS. */
    if (!configurePeerHeartbeat(slave)) {
        goto cleanup;
    }

    spdlog::info(
        "NMT master validation ready on peer node {}; heartbeat={}ms",
        CANOPEN_PEER_NODE_ID, CANOPEN_PEER_HEARTBEAT_MS);
    if (!enterPreOperational(autoStartAfterReset, initialStartObserved)) {
        goto cleanup;
    }

    spdlog::info(
        "Expected formal sequence: START -> STOP -> PREOP -> RESET_COMM "
        "-> RESET_NODE -> START");

    if (!initialStartObserved && !waitForNmtMasterStep(slave, kStartStep)) {
        goto cleanup;
    }
    if (!waitForNmtMasterStep(slave, kStopStep)
        || !waitForNmtMasterStep(slave, kPreOperationalStep)
        || !waitForNmtMasterStep(slave, kResetCommunicationStep)
        || !waitForNmtMasterStep(slave, kResetCommunicationCompletionStep)) {
        goto cleanup;
    }

    if (!waitForFormalCommandAfterReset(slave, kResetNodeStep, autoStartAfterReset)
        || !waitForNmtMasterStep(slave, kResetNodeCommunicationStep)
        || !waitForNmtMasterStep(slave, kResetNodeCompletionStep)
        || !waitForFinalStartAfterReset(slave, autoStartAfterReset)) {
        goto cleanup;
    }

    result = 0;

cleanup:
    unregisterNmtCommandObserver(slave);
    if (result == 0) {
        spdlog::info("NMT master behavior validation passed");
    }
    return result;
}
